# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-24 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GetEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name=b'Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name=b'Last Modified At')),
                ('message_id', models.CharField(blank=True, max_length=50, null=True)),
                ('from_address', models.CharField(max_length=255, verbose_name=b'From')),
                ('to_address', models.CharField(max_length=255, verbose_name=b'To')),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('email_date', models.DateTimeField(blank=True, null=True)),
                ('email_content', models.TextField(verbose_name=b'Body')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name=b'Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name=b'Last Modified At')),
                ('rule_name', models.CharField(max_length=50)),
                ('rule_condition', models.CharField(choices=[(b'ALL', b'ALL'), (b'ANY', b'ANY')], max_length=10)),
                ('rule_criteria', models.TextField(blank=True, null=True, verbose_name=b'Criteria')),
                ('rule_action', models.TextField(blank=True, null=True, verbose_name=b'Action')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
