# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-24 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rules',
            name='apply_filter_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rules',
            name='create_filter_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
